### ISSUE TITLE
Support override of application.properties for AWS Docker image

### ISSUE THREAD

**Issue by jimmie** [NASA-PDS/registry-api#117]
The application.properties in the release image identifies localhost:9200 as the ES endpoint which of course doesn't work in the case of a Docker image for AWS ECR/Fargate. Need to copy in an application.properties file which has been set-up for AWS into the Docker image.

**Comment by al-niessner** [comment]
I use this on the command line:

`--volume /home/niessner/Projects/PDS/registry-api/service/src/main/resources/application.properties.all:/usr/local/registry-${ver}/service/target/classes/application.properties`

You can also have docker compose do similar so that you can have your own away from deployment properties file.
