### ISSUE TITLE
As a user,  I want to query for products from any PDS4 product type

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#12]
@tloubrieu-jpl commented on [Wed May 19 2021](https://github.com/NASA-PDS/registry-api-service/issues/32)

## Motivation
Currently the end-point /products refers to any type of product, including collections and bundles.

So the end-points /products/{lidvid}/bundles  or /products/{lidvid}/collections created for ticket #29 are confusing.

We need to find a better solution for that.

## Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
closed by mistake

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

Can we change `/products*` to `/any*` then make `/products*` do just products without bundles or collections?

**Comment by tloubrieu-jpl** [comment]
We can consider 2 ways to go in the future:

**Explicit end-points:**
/products/
/products/collections
/products/bundles
/products/observations
/products/contexts
/products/documents


**Generic option**
/products?class={product_class}
/products/{identifier}/
/products/{identifier}/children (collections, products)
/products/{identifier}/parents (collections, bundles)

But anyway we are waiting for user feedback to move forward on that.

We will for now update the documentation to make the user cases clear to the users.

**Comment by al-niessner** [comment]
Just adding notes after thinking about it all weekend.

The shortcut (not having to type out a long q=something) is to build endpoints around product class like bundle and collection. However there seems to be a larger set of product classes than bundle and collections. So it seems that we then would have (shortening product class to pc}:

/{pc_1}
/{pc_1}/{lidvid}
/{pc_1}/{lidvid}/all
/{pc_1}/{lidvid}/latest
/{pc_1}/{lidvid}/{pc_2}
/{pc_1}/{lidvid}/{pc_2}/all
/{pc_1}/{lidvid}/{pc_2}/latest

Where pc_1 != pc_2. If we then say that we have N product classes (pc_N) we would have:

number of endpoints = 4*N + 3*(N-1) = 7N - 3

Arguably it should really be because specifying a lidvid should not be limited by product class -- after all the user is specifying a specific lidvid:

/{pc}
/products
/products/{lidvid}
/products/{lid}/all
/products/{lidvid}/latest
/products/{lidvid}/{pc}
/products/{lidvid}/{pc}/all
/products/{lidvid}/{pc}/latest

This would result in:

number of endpoints = 4N + 4 = 4(N+1)

Either way, these turn into a big number fast. The alternative using product class as a parameter would then be 6 total endpoints

/products
/products/all
/products/latest
/products/{lidvid}
/products/{lidvid}/all
products/{lidvid}/latest

If lidvid is supplied, then product class refers to all those product classes that the lidvid references. If no lidvid is given, then only that product class is returned.

**Comment by jordanpadams** [comment]
See comments in https://github.com/NASA-PDS/registry-api/issues/131 and #142 for the design that was decided upon. I&T team will need to come up with various test cases to test the new refactored design
