### ISSUE TITLE
Registry API Service docker container fails to start with error: Unable to access jarfile /usr/local/registry-api-service/registry-api-service.jar

### ISSUE THREAD

**Issue by ramesh-maddegoda** [NASA-PDS/registry-api#128]
The Registry API Service docker container fails to start with error: `Unable to access jarfile /usr/local/registry-api-service/registry-api-service.jar`.

## 📜 To Reproduce

1. Make sure there are no docker images of `registry-api-service` available in the local docker environment
2. git clone https://github.com/NASA-PDS/registry.git
3. cd docker/certs
4. ./generate-certs.sh
5. cd ..
6. docker compose --profile=pds-core-registry up
7. Notice the following error in logs
```

docker-registry-api-1        | Starting Registry API service...
docker-registry-api-1        | Error: Unable to access jarfile /usr/local/registry-api-service/registry-api-service.jar
docker-registry-api-1 exited with code 1

```

## 🕵️ Expected behavior

- The docker container of the registry-api-service is up and running 
- The Swagger UI of the registry-api-service can be accessible from http://<IP_ADDRESS_OF_THE_HOST>:8080

**Comment by tloubrieu-jpl** [comment]
Hi [@Sean C Kelly](https://jpl.slack.com/team/UEDL8N43Y) do you know where the docker build parameters come from in action https://github.com/NASA-PDS/registry-api/runs/6086399996?check_suite_focus=true ? I am wondering why it is using version --build-arg version=0.5.1 since the latest unstable version is 1.1.0-SNAPSHOT in this repository.

**Comment by tloubrieu-jpl** [comment]
From @nutjob4life on slack:

The dockerfile.local which is used for unstable build does not work as expected (it is not consistent with the dockerfile.http)

Temporary conclusion:
Okay so for unstable builds, we need another Dockerfile (or better yet: refactored common Dockerfile) that mimics the layout of the "production" Dockerfile.http&Dockerfile.https but uses the local Maven artifacts instead of those published to OSSRH

To be reviewed at the breakout on Thuraday 04-28.

**Comment by jordanpadams** [comment]
Status: @nutjob4life working on dockerfile for local+https+whatever
