### ISSUE TITLE
JSON response is using HTTP in href references

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#145]
## 📜 To Reproduce
1. Execute `curl -X GET --header 'Accept: application/json' 'https://pds.nasa.gov/api/search-geo/1.0/products?limit=5' | json_pp`

2.
```json
...
         "targets" : [
            {
               "href" : "http://pds.nasa.gov/products/urn:nasa:pds:context:target:planet.mercury",
               "id" : "urn:nasa:pds:context:target:planet.mercury"
            }
         ],
...
         "observing_system_components" : [
            {
               "href" : "http://pds.nasa.gov/products/urn:nasa:pds:context:instrument_host:spacecraft.mess",
               "id" : "urn:nasa:pds:context:instrument_host:spacecraft.mess"
            },
            {
               "href" : "http://pds.nasa.gov/products/urn:nasa:pds:context:instrument:xrs.mess",
               "id" : "urn:nasa:pds:context:instrument:xrs.mess"
            }
         ],
...
etc.
```

## 🕵️ Expected behavior

Anywhere we have `href`, it should be `https://` not `http://`

## 📚 Version of Software Used

API v1.0

**Comment by al-niessner** [comment]
@jordanpadams @jimmie @tloubrieu-jpl 

This is more complicated then you want it to be. It means changing data from the database on the fly -- is that really a good idea even if it is expedient? Also, it may be difficult to find all of the places to update the data since http:// should be changed to https:// for all output data types should it not? The hard part is going to be deciding where need to be changed. href yes or maybe. href as part of targets and observing_system_components but all other without exception or error?

**Comment by al-niessner** [comment]
@jordanpadams @jimmie @tloubrieu-jpl 

Given it a little more thought this morning, if the data is being ingested by harvest this way, then it seems like harvest should be corrected. For ancient data ingested when http:// was allowable then harvest is not a good fix. In the case of ancient data, using Apache to [redirect](https://linuxize.com/post/redirect-http-to-https-in-apache/) seems like the modern approach. This keeps the integrity of the data in opensearch, allows registry-api say that we do not change content despite the fact that we already do, and if https ever changes to httpz then we can Apache do that forwarding as well rather than change the database content yet again.

**Comment by jordanpadams** [comment]
@al-niessner are we sure this is data in harvest? aren't we generating these URLs on the fly from the references?

If not, I am OK with not updating existing data right now (or at least until we have a more robust method for doing so), but we should not be introducing these http URLs into the metadata if they can be avoided, since it is just inaccurate.

**Comment by al-niessner** [comment]
@jordanpadams @jimmie 

It gets pretty confusing actually. There are many references to href and http://pds.nasa.gov but none to http://pds.nasa.gov/products/.

There are two href and http references in this repo all from generated code:

1. XML href for namespace at http://pds.nasa.gov/api
2. various/many documentation references like: JacksonXmlProperty(namespace="http://pds.nasa.gov/api", localName = "title")

However all of these are API references and none of them are product references like what this ticket shows. Therefore, it seems that products reference is from the database itself.

The golden rule for this repository is that it should not modify any of the data that comes from the database. Obviously it translates blobs and some keywords for special characters, but otherwise it should not alter the data it returns. Given this rule, what the user sees is what we have in the database. Will make your life nicer in the future if you keep it that way.

Should update the ticket to move to new API to change over to https if that is the desire for those href (http://pds.nasa.gov/api) as well.


Evidence that they are all API references:

```
$ find . -name \*.java -exec grep 'http://' {} \; -print | grep -v api
 *     http://www.apache.org/licenses/LICENSE-2.0
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/ErrorMessage.java
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/Metadata.java
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/PdsProduct.java
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/PropertyArrayValues.java
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/Reference.java
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/Summary.java
            .licenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html")
./model/target/generated-sources/swagger/src/gen/java/main/io/swagger/configuration/SwaggerDocumentationConfig.java
            .licenseUrl("http://www.apache.org/licenses/LICENSE-2.0.html")
```

and 

```
$ find . -name \*.java -exec grep 'href' {} \; -print
  @JsonProperty("href")
  @JacksonXmlProperty(namespace="http://pds.nasa.gov/api", localName = "href")
  private String href = null;
  public Reference href(String href) {
    this.href = href;
   * @return href
    return href;
  public void setHref(String href) {
    this.href = href;
        Objects.equals(this.href, reference.href) &&
    return Objects.hash(title, id, href, type, description);
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
./model/target/generated-sources/swagger/src/gen/java/main/gov/nasa/pds/model/Reference.java
```

**Comment by jordanpadams** [comment]
@al-niessner

looks like the references [are set here](https://github.com/NASA-PDS/registry-api/blob/main/service/src/main/java/gov/nasa/pds/api/registry/model/SearchUtil.java#L50) which gets the [baseUrl from here](https://github.com/NASA-PDS/registry-api/blob/main/service/src/main/java/gov/nasa/pds/api/registry/controller/SwaggerJavaTransmuter.java#L56).

The `HttpServletRequest` object appears to be returning http instead of https. So I guess we can either hardcode, or this may be useful: https://stackoverflow.com/questions/25911469/request-getscheme-is-returning-http-instead-of-returning-https-in-java

**Comment by al-niessner** [comment]
@jordanpadams @jimmie 

You can find stuff better than me in this code. I vaguely remember playing with code way back when but did not understand it at all when changing it. As you point out it is set using HttpServletRequest.getScheme() which is dependent on how the proxy/loader are set up from your [stackoverflow](https://stackoverflow.com/questions/25911469/request-getscheme-is-returning-http-instead-of-returning-https-in-java). It seems without correct configuration:

1. `proxy_set_header X-Forwarded-Proto  $scheme;` for proxy
2. very load balance implementation dependent

there is no way to scheme right. Depending on being behind a proxy or behind a load balance tool then means we have to get the right scheme different ways. Do we know which is mixing up the scheme? If it is a proxy like Apache, then does that mean it would still be better to simply use Apache to forward http to https as well so that href works anyway? Maybe an Apache forward would work for load balancing as well?

**Comment by jordanpadams** [comment]
@al-niessner 

@jimmie can probably provide more insight, but the API is behind a proxy through AWS.

> Apache to forward http to https
It already does this. The premise behind this ticket is that the metadata is inaccurate. Does it work? Yes. But since this is an API code-thing, I was hoping we could just provide better information.

**Comment by al-niessner** [comment]
@jordanpadams @jimmie 

So does this repo generate all of the metadata?

We can only provide the information we are provided -- which is what is being done. Classic GIGO in that we are told http so we echo that despite it being wrong.

We could override it with a property where we try dynamic look up if property is not defined. Would that do what you want?

**Comment by jordanpadams** [comment]
moving this is icebox since it is nice-to-have but not requried

**Comment by tloubrieu-jpl** [comment]
This has been solved by ticket https://github.com/NASA-PDS/pds-api/issues/253

See screenshot of the service response here:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/60993872/223518152-bb2aae69-a0a5-405c-a7f3-dd3b32d1635c.png">
