### ISSUE TITLE
Sub-project should inherit parent project version in order to be able to automate versioning using mvn commands

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/registry-api#182]
## 🐛 Describe the bug

Whenever the Roundup Action executes `mvn versions:set` it affects only the repository's `pom.xml`. However, [a certain repository whose name will not be spoken](https://github.com/NASA-PDS/registry-api) is a "multi-module" repository whose `pom.xml` contains
```xml
<modules>
    <module>model</module>
    <module>lexer</module>
    <module>service</module>
</modules>
```
But `versions:set` doesn't update the `<version>` specification in child `pom.xml` files.

Apparently instead of just

    mvn -DnewVersion=1.2.3 versions:set

Rounup needs to do

    mvn -DnewVersion=1.2.3 -DprocessAllModules=true -DartifcatId=* -DgroupId=* versions:set

## 🕵️ Expected behavior

In `registry-api`, all `pom.xml` files should be updated after `versions:set`.

## 📚 Version of Software Used

`roundup-action@stable`

---

**Comment by jordanpadams** [comment]
@nutjob4life I think this bug is because when the new repo was created, each sub-project was trying to maintain their own version, which obviously doesn't work when we want to support this multi-project repo. We should update the sub-repos to no longer have their own versions, and instead just set the [parent repo](https://github.com/NASA-PDS/pds4-information-model/blob/main/model-lddtool/pom.xml#L35)

**Comment by jordanpadams** [comment]
if you agree, I will move this ticket to the registry-api repo

**Comment by nutjob4life** [comment]
@jordanpadams works for me!
