### ISSUE TITLE
Add CORS header to registry API deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#189]
## 💡 Description

We need the Search UI  that @eddiesarevalo develops to access the registry API, for example https://pds.nasa.gov/api/search-en-gamma/1.1/classes/collections?keyword=insight from a different host (hosting the UI code)

For that to work we need to add the CORS attribute to the registry API:

`Access-Control-Allow-Origin: *`

See comments for details https://github.com/NASA-PDS/registry-api/issues/189#issuecomment-1317376810

**Comment by tloubrieu-jpl** [comment]
@jimmie we discuss that today during the breakout, you can discuss with @tloubrieu-jpl and @eddiesarevalo what is actually needed.

**Comment by eddiesarevalo** [comment]
Hey @jimmie I'm not sure exactly how to configure the server to allow CORS since I'm not a server expert but doing a search for it I found this article: https://www.bannerbear.com/blog/what-is-a-cors-error-and-how-to-fix-it-3-ways/

From there it says to set this: `set the header to Access-Control-Allow-Origin: * to allow requests from any URL`

This part:
_Solution 1: Configure the Backend to Allow CORS_

_If you have access to the backend service, you can configure the backend to handle CORS requests if they are allowed._

_The basic requirement is to add Access-Control-Allow-Origin to the response header to specify the origin that is allowed to access resources from the server._

_You can configure the backend to return this in the response header:_

_Access-Control-Allow-Origin: https://domain-a.com
This will allow https://domain-a.com to make a cross-origin request to your server. However, only an origin can be added._

_If you want to allow multiple origins, you can do it dynamically by reading the Origin header from the request and set it as the value for Access-Control-Allow-Origin._

_Another option would be to set the header to Access-Control-Allow-Origin: * to allow requests from any URL. However, you need to be careful when using this as it could cause your server to be vulnerable to CSRF attacks._

Since [https://pds.nasa.gov/api/search-en-gamma/1.1/](https://pds.nasa.gov/api/search-en-gamma/1.1/classes/collections?keyword=insight) is a dev version of the api it should be ok to allow access control. 

Also I only need GET requests so if you want to keep some security so that POST DELETE etc stay protected it should be fine.

**Comment by eddiesarevalo** [comment]
@jimmie I'm not sure of the server we are using here but here is a page listing how to do it for different servers:

https://enable-cors.org/server.html

For example apache:

https://enable-cors.org/server_apache.html

**Comment by jimmie** [comment]
I will discuss how best to support this w/ the SAs at today's office hour.

Added a CloudFront function to add header (restricted to jpl.nasa.gov domains for now) to responses. SA's associated the function with both pds.nasa.gov and pds.jpl.nasa.gov distributions.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo can you test the access to the API from a UI called as follow http://{name of your laptop}.jpl.nasa.gov/...

You will be able to 'serve' your developed application under that host name if you are connected to the VPN.

**Comment by tloubrieu-jpl** [comment]
The CORS header `Access-Control-Allow-Origin: *.jpl.nasa.gov` has been added this is sufficient for JPL internal developers to work with the API whch is enough to enable the development of the Search UI by @eddiesarevalo for now.

In the future we also want to add '*.launchbox.run' to the allowed domain or 'localhost.launchbox.run' so that external developers can use the API without a need to ask for specific authorization. See ticket https://github.com/NASA-PDS/registry-api/issues/192
