### ISSUE TITLE
/classes endpoint does not work in a browser

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#200]
## 🐛 Describe the bug

I believe this can be reproduced with curl request:
`curl http://localhost:8081/classes -H 'Accept:text/html'`

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl I replicated this (having neglected to update `main` from its few-week-old version) and [wrote a fix](https://github.com/NASA-PDS/registry-api/compare/main...220-classes-browser-serialization), but with an updated version of `main` I'm no longer able to replicate it.  I thought it might have been incidentally resolved in 87814ae2 or 1ce13065, but it's non-reproducible even as of revision e2162a11 (and going much further back is turning out to be more of a pain than it's worth due to environment minutiae).

Suggest closing as it's no longer reproducible, but it's relevant that [`ClassesSerializer`](https://github.com/NASA-PDS/registry-api/blob/9bc721c50dd0e6bd8f7075bc548cdc6a827783cb/service/src/main/java/gov/nasa/pds/api/registry/view/ClassesSerializer.java#L16) is [not included in the converters](https://github.com/NASA-PDS/registry-api/blob/9bc721c50dd0e6bd8f7075bc548cdc6a827783cb/service/src/main/java/gov/nasa/pds/api/registry/configuration/WebMVCConfig.java#L64) and it's still the case that the log message is in the wrong place (it checks size before anything's actually added, so always logs zero converters) so that fix (ae6ce917) should still make it in.

Should the ClassesSerializer be added to the converters, or deleted from the codebase, given that it appears unnecessary?

**Comment by tloubrieu-jpl** [comment]
Right I am not reproducing it either, this has been field without knowing as a consequence of ticket https://github.com/NASA-PDS/registry-api/issues/248
