### ISSUE TITLE
Pagination not working as expected with /collections/{identifier}/products

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/registry-api#240]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

@jordanpadams thought the [deep-archive](https://github.com/NASA-PDS/deep-archive/) was paginating incorrectly. I know it worked at one time.

The [documentation](https://nasa-pds.github.io/pds-api/specifications/search-v1.0.0-redoc.html#operation/products-of-a-collection) says the `limit` is a cardinal, telling _how many_ to return. But he suspected that it might now be an ordinal, telling the _end index_ of the row to return.

I [tested both extensively in a comment on a separate issues](https://github.com/NASA-PDS/deep-archive/issues/140#issuecomment-1404269589) and found that it's neither. It's sort of just broken.

### 🕵️ Expected behavior

I expected to paginate by using `start` and `limit` parameters, preferably with `limit` telling _how many_ to return.

### 📜 To Reproduce

```bash
See https://github.com/NASA-PDS/deep-archive/issues/140#issuecomment-1404269589
```

### 🖥 Environment Info

```bash
- https://pds.nasa.gov/api/search/1.0 as of 2023-01-26
```

### 📚 Version of Software Used

- https://pds.nasa.gov/api/search/1.0 as of 2023-01-26

### 🦄 Related requirements

N/A

### ⚙️ Engineering Details

May be tightly coupled with https://github.com/NASA-PDS/registry-api/issues/231

**Comment by alexdunnjpl** [comment]
Need to reproduce, and also confirm that there is no ambiguity with the OpenSearch window and/or end limitations (~10k-50k).  Some OpenSearch deployments have been upped to a non-limit of 2^32, but some may not have, and this can yield similar "symptoms".

**Comment by alexdunnjpl** [comment]
Have replicated @nutjob4life 's results - there appears to be some erroneous and/or doubled slicing going on during PaginationLidvidBuilder.addAll().

N.B. This does *not* affect other endpoints, for example `/collections?start=2&limit=1` works correctly given a cursory manual test.

This is closely related to #250, which complicates testing somewhat.

Continuing with this issue as priority-1

**Comment by nutjob4life** [comment]
Thanks @alexdunnjpl! 
![I'm rooting for you!](https://user-images.githubusercontent.com/814813/219472804-408ae9bd-8a8c-472b-b0f4-b79c3eb67e13.gif)

**Comment by alexdunnjpl** [comment]
[Relevant discussion here](https://github.com/NASA-PDS/registry-api/issues/231#issuecomment-1431947650).

Taking the definitions:
 - "inner page" => the collection of LIDVIDs returned in a single OpenSearch `SearchHit` (currently size 500)
 - "outer page" => the pages of size `HitIterator.size` which correspond with the number of `SearchHit`s to ask for in each request to OpenSearch
 
 Current behaviour appears to be that the slicing desired on the basis of `start` and `limit` is
 - performed on each inner page rather than on the full result set (i.e. the complete concatenation of all outer pages)
 - performed incorrectly (slice from `start` *to* `limit`, rather than from `start` *for* `limit`)

@al-niessner as far as I can see the `PaginationLidvidBuilder` is just built in a way that's fundamentally incompatible with being able to call [`.addAll()`](https://github.com/NASA-PDS/registry-api/blob/main/service/src/main/java/gov/nasa/pds/api/registry/model/PaginationLidvidBuilder.java#L23-L36) multiple times.  Is there any additional context I'm about to stub my toe on, or was this just an oversight?

Looks like `PaginationLidvidBuilder` should just hold the full dataset, and serve elements `start` through `start+limit` when `page()` is called?  Any required sorting behaviour (from the default or the user's query param) would also need to be included in `page()` too, no?  Or is the intent that any sorting be performed db-side and therefore `PaginationLidvidBuilder` 
 - can assume input collections passed to `.addAll()` are ordered both internally and with respect to each other
 - only needs to `add()` data spanning index 0 through `start+limit` without considering anything further (this functionality doesn't appear to be present but should be trivial to add without breaking anything)

?

**Comment by al-niessner** [comment]
@alexdunnjpl 
> @al-niessner as far as I can see the `PaginationLidvidBuilder` is just built in a way that's fundamentally incompatible with being able to call [`.addAll()`](https://github.com/NASA-PDS/registry-api/blob/main/service/src/main/java/gov/nasa/pds/api/registry/model/PaginationLidvidBuilder.java#L23-L36) multiple times. Is there any additional context I'm about to stub my toe on, or was this just an oversight?
> 
> Looks like `PaginationLidvidBuilder` should just hold the full dataset, and serve elements `start` through `start+limit` when `page()` is called? Any required sorting behaviour (from the default or the user's query param) would also need to be included in `page()` too, no? Or is the intent that any sorting be performed db-side and therefore `PaginationLidvidBuilder`
> 
> * can assume input collections passed to `.addAll()` are ordered both internally and with respect to each other
> * only needs to `add()` data spanning index 0 through `start+limit` without considering anything further (this functionality doesn't appear to be present but should be trivial to add without breaking anything)
> 

The whole point pf the builder is to allow you to call addAll() as many times as necessary but rather than hold all 100 TB of data in memory, just hold the page that needs to be returned to the user. Why keep 100 TB of data when the user just asked for start=101010 limit=10 because they have a TRS 80 with a traditional Z80 that can only hold 65 KB?

One of the idiosyncrasies of opensearch that we leverage that is going to bite us in the future is that the results are returned in the same order each time despite us not requesting a sorted order. Again it is from our abuse of a search tool for a database server. The search tool sorts it by relevance unless given another sort algorithm. Hence, it returns the same order each time. Hence, builder does not need all 100 TB to sort it because opensearch already has.

**Comment by alexdunnjpl** [comment]
Thanks @al-niessner. So, non-OpenSearch-default-sort questions aside, we do in fact want `PaginationLidvidBuilder` to 

 - Accumulate input count and drop inputs until it hits the `start`th input
 - Stop storing inputs when the `start+limit`th input has been stored
 - Maybe add an `isComplete()` method that could provide callers with the ability to stop adding when pointless?  Not sure if this actually saves much time given that it's just the cost of exhausting the `HitIterator`, especially since we bumped the `HitIterator.size` to the point that it will rarely make multiple OpenSearch requests.

As a separate issue (#250 ) currently, [it seems like the expectation is](https://github.com/NASA-PDS/registry-api/issues/247#issuecomment-1433565808) that we should *always* be explicitly requesting a sort order from OpenSearch, because the API should default to lidvid-lexical sort.  It doesn't appear to be doing that currently.  Given what you've said, should I proceed assuming that the general "pass the sort type from the user request to OpenSearch" stuff works properly, and that the issue is most-likely that the API isn't passing a sort type in the default case?

**Comment by al-niessner** [comment]
> Thanks @al-niessner. So, non-OpenSearch-default-sort questions aside, we do in fact want `PaginationLidvidBuilder` to
> 
> * Accumulate input count and drop inputs until it hits the `start`th input
> * Stop storing inputs when the `start+limit`th input has been stored
> * Maybe add an `isComplete()` method that could provide callers with the ability to stop adding when pointless?  Not sure if this actually saves much time given that it's just the cost of exhausting the `HitIterator`, especially since we bumped the `HitIterator.size` to the point that it will rarely make multiple OpenSearch requests.
> 
> As a separate issue (#250 ) currently, [it seems like the expectation is](https://github.com/NASA-PDS/registry-api/issues/247#issuecomment-1433565808) that we should _always_ be explicitly requesting a sort order from OpenSearch, because the API should default to lidvid-lexical sort. It doesn't appear to be doing that currently. Given what you've said, should I proceed assuming that the general "pass the sort type from the user request to OpenSearch" stuff works properly, and that the issue is most-likely that the API isn't passing a sort type in the default case?

@alexdunnjpl 

No need for add complete. The problem is that you need to count all the way to the end. You cannot assume 500 per product_lidvids not can assume that 5000 is the upper limit. Therefore, despite the page being full, need to run to the end so that hits in the summary is the total available not total till page is full or bad math with assumptions about what was maybe found already. Bonus is that only the lidvids are being loaded at this point and only the output blobs are loaded for the page. Should minimize memory and network traffic which minimizes the overhead to compute the total hits in the summary.

**Comment by alexdunnjpl** [comment]
Oh, got it - I forgot that it was calculating the hits too.

**Comment by alexdunnjpl** [comment]
@nutjob4life @jordanpadams I've fixed the bug in question, but from what I'm seeing (N.B. #250) there is no reason to expect to be able to trust the data coming out of a paginated set of requests to the endpoint - it's likely there will be missing or duplicate data.

**Comment by nutjob4life** [comment]
> there is no reason to expect to be able to trust the data coming out of a paginated set of requests to the endpoint - it's likely there will be missing or duplicate data.

Sounds like we'll need yet another issue to track this latest wrinkle.

**Comment by al-niessner** [comment]
> > there is no reason to expect to be able to trust the data coming out of a paginated set of requests to the endpoint - it's likely there will be missing or duplicate data.
> 
> Sounds like we'll need yet another issue to track this latest wrinkle.

@alexdunnjpl @jordanpadams @nutjob4life 

Actually, I want to know why we think it will be incomplete or duplicates. It would mean that we have duplicate lidvids in the database or references that do not exist. Either way, it way beyond the purview (remit) of registry-api.

As to sorting during the search, why? It already searches based on relevance (some score assigned by opensearch). The beautiful part is that the lidvids are stored as strings in the database and so you cannot sort the vids correctly anyway. Not sure that opensearch is going to be thrilled with learning how to sort vids correctly either - elasticsearch was not when I looked at years ago but that may have been limited more by my understanding of it than what it offered.
