### ISSUE TITLE
SBN PSI data sets ingested with past version of tools and fields are not searchable

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-api#288]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tried to search for OREX OVIRS data, I cannot search with dataset-specific fields (e.g. target_range). Looking at SBN-PSI kibana dashboard, I also notice they have a limited number of fields, and `target_range` is not one of them.

### 🕵️ Expected behavior

I expected to be able to search by any metadata attribute

### 📜 To Reproduce

See https://github.com/NASA-PDS/registry-api/issues/287

### 📚 Version of Software Used

???

### 🦄 Related requirements

🦄 https://github.com/NASA-PDS/registry/issues/153

**Comment by tloubrieu-jpl** [comment]
@mdrum were you able to progress on the re-ingestion of your products in the registry ? Thanks

Note that we have a new beta release of the registry-harvest components (both standalone and services). You'll find them in their github repository. Let us know if you have questions.

**Comment by mdrum** [comment]
Unfortunately, a security audit of the harvest infrastructure found it to be insufficient protection of our archived data, so any harvesting has stalled, and we have not been able to move forward. We are going to be working with new IT personnel to design a way to run EN software in a no-trust environment, as it is untenable to allow that software to be on the same network, much less machine, as archived data. Copying petabyes of data is also not a feasible solution.

If there are plans to allow the registry-harvest components to run over HTTP or something similar, rather than crawling a file system, that would also alleviate this problem.

**Comment by tloubrieu-jpl** [comment]
Sorry to hear that @mdrum, the performances of crawling the archive over HTTP would not be good but we can consider that.
Besides, what were the security audit exact conclusion ? Is there anything we can do on the crawler itself to make it acceptable for you to deploy next to your archive ? Is that an issue with the HTTP API opened on the harvest services ? Thanks

**Comment by mdrum** [comment]
Due to a system intrusion several years ago, we revamped security at PSI with the requirement that basically no software can run on the server that hosts our archive data on the web, and that server is in a completely isolated network. We previously were using a read-only mount that crossed the firewall in order to access the data, but that was still later found to be too compromising. We're not really sure how other nodes handle this security problem, but for us we need it to be isolated. 

As I said we are now consulting with additional people to evaluate if a compromise can be made, but in lieu of that we would need any software that interacts with our live archived data to work over the public internet.

**Comment by jordanpadams** [comment]
@mdrum ok. we will work around this for now by downloading all of your data and ingesting it from our on-prem systems. in the future, we will plan to use AWS and Nucleus to push this data to the cloud and process there.

would we be able to run our data upload software alongside the data, like we are planning for CSS? or is that also not possible?

**Comment by mdrum** [comment]
That's a good point. I think we'll have the same problem with DUM as with Harvest. I'll bring that up today, hopefully we can find an internal solution. I imagine other nodes don't work under these same security restrictions.

**Comment by tloubrieu-jpl** [comment]
Since this ticket is blocking the demo we want to do with the search API, as an alternative I am creating a new ticket to harvest the Orex dataset in EN registry. The registry will still reference the datasets published on SBN-PSI web. https://github.com/NASA-PDS/registry/issues/196

**Comment by jordanpadams** [comment]
closing this for https://github.com/NASA-PDS/software-issues-repo/issues/79
