### ISSUE TITLE
Remove the 'products' in the /classes

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#326]
## 💡 Description

`products` stands for anything except `bundles` and `collections`.

I don't remember of a use case for that. If it is confirmed I would prefer to remove it, because any use of the `products` keyword outside its PDS4 meaning (any digital artifact) will be confusing for the users.

**Comment by alexdunnjpl** [comment]
I have confirmed that `/classes/products` results in a constraint of `product_class not in [Product_Bundle, Product_Collection]`, per @tloubrieu-jpl 's assertion.

@tloubrieu-jpl @jordanpadams for consistency, it's desirable to implement `/classes/{class}` for all enumerated classes. I'm unsure whether it's possible to excise the concept of `Product`/`RefLogicProduct` (which is what `product` refers to in `/classes/products`) completely.  @al-niessner sing out if you have any input on that score, else I'll dig into the code myself later.

Due to the existence of enum-class `any`, it seems undesirable to just have `/classes/{products}` return all products (though this may be the least-worst option).

**Comment by alexdunnjpl** [comment]
@jordanpadams I'm still not 100% on the PDS4 taxonomy - are there non-aggregate products which are neither document nor observational, or is every non-aggregate one of those two types?

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl see summary of #328 for how I implemented it in the end (and feel free to kick it back if there's a more-preferred way)

**Comment by jordanpadams** [comment]
> @jordanpadams I'm still not 100% on the PDS4 taxonomy - are there non-aggregate products which are neither document nor observational, or is every non-aggregate one of those two types?

@alexdunnjpl there are many non-aggregate products that are neither Product_Document or Product_Observational. API on supports this 2 right now, but eventually we probably want to support all possible product classes.

https://pds.nasa.gov/datastandards/documents/im/current/index_1J00.html#attribute_pds_identification_area_pds_product_class

**Comment by alexdunnjpl** [comment]
That being the case, the `Product*` constructs (now renamed `NonAggregateProduct*`) must stay as-is and the approach in the PR is justified.
