### ISSUE TITLE
API works for a q= string using eq not fails for ne

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/registry-api#402]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When executing a q= query with eq the search works, but the same query with ne gives a 500 error. 

### 🕵️ Expected behavior

I expected valid queries to execute correctly.

### 📜 To Reproduce

This works:
```
$ curl --get --url 'https://pds.nasa.gov/api/search/1/products' --data-urlencode 'q=pds:Citation_Information.pds:author_list eq "abc"' --data-urlencode 'limit=100'

{"summary":{"q":"pds:Citation_Information.pds:author_list eq \"abc\"","hits":0,"took":41,"start":0,"limit":100,"sort":[],"properties":[]},"data":[]}
```
But this does not:
```
$ curl --get --url 'https://pds.nasa.gov/api/search/1/products' --data-urlencode 'q=pds:Citation_Information.pds:author_list ne "abc"' --data-urlencode 'limit=100'

{"timestamp":1701868636837,"status":500,"error":"Internal Server Error","path":"/products"}
```

### 🖥 Environment Info

- curl 8.1.2
- Version of API deployed on 12/06/2023

### 📚 Version of Software Used

API v1.2

### 🩺 Test Data / Additional context

N/A

### 🦄 Related requirements

N/A

### ⚙️ Engineering Details

Most likely an issues with the lexer being applied to the query

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams @tloubrieu-jpl 

Cannot duplicate with most recent code (yes, URL is different and so is the amount of data):

```
$ curl --get --url 'http://localhost:8080/products' --data-urlencode 'q=pds:Citation_Information.pds:author_list eq "abc"' --data-urlencode 'limit=100'
{"summary":{"q":"pds:Citation_Information.pds:author_list eq \"abc\"","hits":0,"took":17,"search_after":[],"limit":100,"sort":[],"properties":[]},"data":[]}

$ curl --get --url 'http://localhost:8080/products' --data-urlencode 'q=pds:Citation_Information.pds:author_list ne "abc"' --data-urlencode 'limit=100'
{"summary":{"q":"pds:Citation_Information.pds:author_list ne \"abc\"","hits":38,"took":155,"search_after":[],"limit":100,"sort":[],><...snip...><
```

We have two options here. We can push until next release and test again on the PDS node while looking at the log files because it may be an out of memory problem in either registry-api with 100 products being too big or an opensearch memory usage problem. We can claim it fixed and close the ticket. Either way, nothing to be done here today nor is it a current code problem in the sense that there is something wrong with ne. My suggestion is to close this ticket and open a new one to test memory usage using ne to see if and what problems it generates to return every known product.

**Comment by jordanpadams** [comment]
@al-niessner can you verify this works as well?

```
((pds:Target_Identification.pds:type eq "Calibrator") and (ref_lid_target ne ""))
```

i.e. show me everything where the target is of type calibrator and has a reference LID set for the target (not just a name).

**Comment by al-niessner** [comment]
> @al-niessner can you verify this works as well?
> 
> ```
> ((pds:Target_Identification.pds:type eq "Calibrator") and (ref_lid_target ne ""))
> ```
> 
> i.e. show me everything where the target is of type calibrator and has a reference LID set for the target (not just a name).

Still working at standing up my registry again to test this, but this will not do what you think it will. If what you want is id type Calibrator AND has a ref_lid_target then this will not do the job. It says id type Calibrator AND not ref_lid_target being exactly "". For opensearch the not ref_lid_target being exactly  "" also includes those that do not have a ref_lid_target at all since it cannot be "". If you want ref_lid_target exists then we need to update the language a bit more.

**Comment by jordanpadams** [comment]
@al-niessner copy. so sounds like we need to create some ability to say `is not null` or `exists`. Looks like OpenSearch uses `exists` so may be best to just go that route. Will create a new requirement. https://opensearch.org/docs/latest/query-dsl/term/exists/

**Comment by jordanpadams** [comment]
Closing this since it appears `ne` is supported, but this is actually a new requirement for supporting `exists`. https://github.com/NASA-PDS/registry-api/issues/406
